# Generated by Django 5.0.3 on 2024-03-19 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fonctionnement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="ticket",
            new_name="title",
        ),
    ]
