# Generated by Django 5.0.3 on 2024-03-20 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fonctionnement", "0002_rename_ticket_ticket_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="caption",
        ),
    ]
